### ISSUE TITLE
Sourcemap is not working in the renderer

### ISSUE THREAD

**Issue by remss** [electron/electron-quick-start-typescript#11]
- Add a `console.log()` and a  `debugger;` in renderer.ts
- Run `npm start`
- Open devtools
- The console.log is not mapped to src/renderer.ts but dist/renderer.js

![image](https://user-images.githubusercontent.com/1586257/42498297-14ee2132-842c-11e8-8e25-36dd5049379f.png)

Sourcemap seems correct to me and I wonder if it may be an electron issue...

electron-quick-start-typescript version 2cc1f0f7d5dad2da98a092a1d18be72051284f16
electron version 2.0.2
tsc version  2.7.2

**Comment by remss** [comment]
This is an Electron issue.
https://github.com/electron/electron/issues/13730

**Comment by saostad** [comment]
get sourcemaps working by enabling both inlineSourceMap and inlineSources in tsconfig.json.
