### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by leonheess** [electron/electron-quick-start-typescript#180]
Works perfectly fine on my Windows machine but if I try to start it with macOS I get a white screen as if the preload script is never reached

**Comment by ilya-skoropad** [comment]
i have the same error

**Comment by leonheess** [comment]
@ilya-skoropad I did some testing and I could narrow the issue down to using a virtual macOS machine. So I bought a real one off eBay and it works perfectly fine there..
