### ISSUE TITLE
Sharing global object

### ISSUE THREAD

**Issue by Leonardonline** [electron/electron-quick-start-typescript#19]
The [documentation](https://electronjs.org/docs/faq#how-to-share-data-between-web-pages) shows how to share data between pages:

```
// In the main process.
global.sharedObject = {
  someProperty: 'default value'
}
```
but with Typescript version, we get this error:

> error TS2339: Property 'sharedObject' does not exist on type 'Global'.

**Comment by theJian** [comment]
```ts
interface SharedObject {
  someProperty: string;
};

declare const sharedObject: SharedObject = { ... }
```
Does it work for you?

**Comment by Leonardonline** [comment]
I tried but it doesn't work, it doesn't get the data.

**Comment by Leonardonline** [comment]
Here a repo where I replicate my error and @theJian solution, but unfortunately not working

https://github.com/Leonardonline/electron-quick-start-typescript

**Comment by Leonardonline** [comment]
I solved using:

```js
(<any>global).sharedObject = { 
  someProperty: string
};
```

**Comment by wuqingabc** [comment]
@Leonardonline Thank you. I faced the same issue and your solution helped!

**Comment by tothambrus11** [comment]
`
declare namespace global{
    let settingsService: SettingsService
}
`

So you can write `global.settingService`

**Comment by Silvano14** [comment]
> Create a global.d.ts file in your project.
> 
> ```ts
> declare namespace NodeJS{
>     export interface Global {
>         myVar: number
>     }
> }
> ```
> 
> This will merge the base NodeJS declarations with yours, so you can write `global.myVar` in your code. I couldn't figure out how to specify existing interfeces, so I use : any for my global settingsService

fake...

In the global.d.ts: 

`declare namespace NodeJS {
  export interface Global {
    certificateInfo: { trusted: boolean; url: string };
  }
}`

`console.log(global.certificateInfo); // got undefined`
