### ISSUE TITLE
npm start not work

### ISSUE THREAD

**Issue by ahmedNY** [electron/electron-quick-start-typescript#28]
![image](https://user-images.githubusercontent.com/14958972/67600705-eada0580-f772-11e9-9373-85475b513e6c.png)

**Comment by jo-wu** [comment]
...Did you run npm install before npm start?

**Comment by ahmedNY** [comment]
Yes

**Comment by jo-wu** [comment]
I just run this sample successfully, I can't figure your problem out, cause I am new to it too.
but I think your problem is in your developer enviroment, below is mine:
    ubuntu 16.04
    node  v12.13.0
    npm  6.12.0
    "electron": "^6.0.8",
    "typescript": "^3.6.0"
I hope this might help you solve the problem

**Comment by rollerkazike** [comment]
I had the same issue trying to run the app after a simple and clean npm i + npm start. No errors, no messages, nothing, just a window that was supposed to open... won't open.

Solved the issue cleaning the cache (removing the folders) of all my electron apps in AppData > Roaming as it's explained here: https://github.com/electron-userland/electron-prebuilt-compile/issues/36

I'm running the examples on a Windows 10 64bits.
