### ISSUE TITLE
Type 'null' is not assignable to type 'BrowserWindow'.

### ISSUE THREAD

**Issue by andrewrynhard** [electron/electron-quick-start-typescript#35]
```
$ tsc
main.ts:27:5 - error TS2322: Type 'null' is not assignable to type 'BrowserWindow'.

27     mainWindow = null
       ~~~~~~~~~~


Found 1 error.
```

**Comment by NetOperatorWibby** [comment]
```ts
let mainWindow: Electron.BrowserWindow;
```

**Comment by KBeDeveloper** [comment]
I think this should be handled with *mainWindow.[destroy()](https://www.electronjs.org/docs/api/browser-window#windestroy)* or with a (hypothetically) purge() method instead of a *null* assignment... With this electron logic, the example code seems to not make sense :/
