### ISSUE TITLE
Replace TSLint with ESLint

### ISSUE THREAD

**Issue by serkonda7** [electron/electron-quick-start-typescript#36]
Due to the fact, that TSLint was deprecated by the developer, it should be replaced with the better ESLint.

**Comment by GuilhermeRossato** [comment]
By the way, this is how to do it to your project:

```
npm remove tslint
npm install eslint --save-dev
rm tslint.json
````

Then edit package.json's `script` property at "lint" to `eslint -c eslint.json ./src/**/*.ts`.

Initialize eslint config by calling `npm run eslint -- --init`

And you're done, run `npm run eslint` when you want to see its proverbs and `npm run eslint --fix` to correct them.
